# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_extrandpoints.ui'
#
# Created: Mon Oct 29 16:16:23 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_extgen(object):
    def setupUi(self, extgen):
        extgen.setObjectName(_fromUtf8("extgen"))
        extgen.resize(534, 417)
        self.tabWidget = QtGui.QTabWidget(extgen)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 511, 341))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabVector = QtGui.QWidget()
        self.tabVector.setObjectName(_fromUtf8("tabVector"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabVector)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 491, 304))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.inShape = QtGui.QComboBox(self.verticalLayoutWidget)
        self.inShape.setObjectName(_fromUtf8("inShape"))
        self.verticalLayout_2.addWidget(self.inShape)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnUpdate = QtGui.QToolButton(self.verticalLayoutWidget)
        self.btnUpdate.setObjectName(_fromUtf8("btnUpdate"))
        self.horizontalLayout.addWidget(self.btnUpdate)
        self.btnCanvas = QtGui.QToolButton(self.verticalLayoutWidget)
        self.btnCanvas.setObjectName(_fromUtf8("btnCanvas"))
        self.horizontalLayout.addWidget(self.btnCanvas)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.xMin = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.xMin.setReadOnly(True)
        self.xMin.setObjectName(_fromUtf8("xMin"))
        self.gridLayout_2.addWidget(self.xMin, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.xMax = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.xMax.setReadOnly(True)
        self.xMax.setObjectName(_fromUtf8("xMax"))
        self.gridLayout_2.addWidget(self.xMax, 1, 1, 1, 1)
        self.yMin = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.yMin.setReadOnly(True)
        self.yMin.setObjectName(_fromUtf8("yMin"))
        self.gridLayout_2.addWidget(self.yMin, 0, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.yMax = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.yMax.setReadOnly(True)
        self.yMax.setObjectName(_fromUtf8("yMax"))
        self.gridLayout_2.addWidget(self.yMax, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_2.addWidget(self.label_12)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.site = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.site.setObjectName(_fromUtf8("site"))
        self.horizontalLayout_7.addWidget(self.site)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_8.addWidget(self.label_11)
        self.country = QtGui.QComboBox(self.verticalLayoutWidget)
        self.country.setObjectName(_fromUtf8("country"))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.country.addItem(_fromUtf8(""))
        self.horizontalLayout_8.addWidget(self.country)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_2.addWidget(self.label_8)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.outShape = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName(_fromUtf8("outShape"))
        self._2.addWidget(self.outShape)
        self.toolOut = QtGui.QToolButton(self.verticalLayoutWidget)
        self.toolOut.setObjectName(_fromUtf8("toolOut"))
        self._2.addWidget(self.toolOut)
        self.verticalLayout_2.addLayout(self._2)
        self.tabWidget.addTab(self.tabVector, _fromUtf8(""))
        self.tabAbout = QtGui.QWidget()
        self.tabAbout.setObjectName(_fromUtf8("tabAbout"))
        self.label_10 = QtGui.QLabel(self.tabAbout)
        self.label_10.setGeometry(QtCore.QRect(20, 5, 451, 221))
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tabAbout, _fromUtf8(""))
        self.label_13 = QtGui.QLabel(extgen)
        self.label_13.setGeometry(QtCore.QRect(10, 390, 347, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.buttonBox = QtGui.QDialogButtonBox(extgen)
        self.buttonBox.setGeometry(QtCore.QRect(343, 360, 181, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))

        self.retranslateUi(extgen)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), extgen.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), extgen.reject)
        QtCore.QMetaObject.connectSlotsByName(extgen)

    def retranslateUi(self, extgen):
        extgen.setWindowTitle(QtGui.QApplication.translate("extgen", "Generate random site from extent", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("extgen", "<html><head/><body><p><span style=\" font-weight:600;\">Select Layer</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUpdate.setText(QtGui.QApplication.translate("extgen", "Update extent from layer", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCanvas.setText(QtGui.QApplication.translate("extgen", "Update extent from canvas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("extgen", " x Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("extgen", "y Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("extgen", " x Min", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("extgen", "y Max", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("extgen", "<html><head/><body><p><span style=\" font-weight:600;\">Enter name of site and select country</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("extgen", "Site Name* ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("extgen", "Country (For Many countries leave blank)", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(0, QtGui.QApplication.translate("extgen", "--select--", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(1, QtGui.QApplication.translate("extgen", "Cote d\'Ivoire", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(2, QtGui.QApplication.translate("extgen", "Angola", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(3, QtGui.QApplication.translate("extgen", "Burkina Faso", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(4, QtGui.QApplication.translate("extgen", "Burundi", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(5, QtGui.QApplication.translate("extgen", "Benin", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(6, QtGui.QApplication.translate("extgen", "Botswana", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(7, QtGui.QApplication.translate("extgen", "Congo, DRC", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(8, QtGui.QApplication.translate("extgen", "Central African Republic", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(9, QtGui.QApplication.translate("extgen", "Congo", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(10, QtGui.QApplication.translate("extgen", "Cameroon", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(11, QtGui.QApplication.translate("extgen", "Djibouti", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(12, QtGui.QApplication.translate("extgen", "Algeria", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(13, QtGui.QApplication.translate("extgen", "Egypt", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(14, QtGui.QApplication.translate("extgen", "Western Sahara", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(15, QtGui.QApplication.translate("extgen", "Eritrea", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(16, QtGui.QApplication.translate("extgen", "Ethiopia", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(17, QtGui.QApplication.translate("extgen", "Gabon", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(18, QtGui.QApplication.translate("extgen", "Ghana", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(19, QtGui.QApplication.translate("extgen", "The Gambia", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(20, QtGui.QApplication.translate("extgen", "Guinea", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(21, QtGui.QApplication.translate("extgen", "Equatorial Guinea", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(22, QtGui.QApplication.translate("extgen", "Guinea-Bissau", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(23, QtGui.QApplication.translate("extgen", "Kenya", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(24, QtGui.QApplication.translate("extgen", "Comoros", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(25, QtGui.QApplication.translate("extgen", "Liberia", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(26, QtGui.QApplication.translate("extgen", "Lesotho", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(27, QtGui.QApplication.translate("extgen", "Libya", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(28, QtGui.QApplication.translate("extgen", "Morocco", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(29, QtGui.QApplication.translate("extgen", "Madagascar", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(30, QtGui.QApplication.translate("extgen", "Mali", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(31, QtGui.QApplication.translate("extgen", "Mauritania", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(32, QtGui.QApplication.translate("extgen", "Mauritius", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(33, QtGui.QApplication.translate("extgen", "Malawi", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(34, QtGui.QApplication.translate("extgen", "Mozambique", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(35, QtGui.QApplication.translate("extgen", "Namibia", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(36, QtGui.QApplication.translate("extgen", "Niger", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(37, QtGui.QApplication.translate("extgen", "Nigeria", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(38, QtGui.QApplication.translate("extgen", "Reunion", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(39, QtGui.QApplication.translate("extgen", "Rwanda", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(40, QtGui.QApplication.translate("extgen", "Seychelles", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(41, QtGui.QApplication.translate("extgen", "Sudan", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(42, QtGui.QApplication.translate("extgen", "Sierra Leone", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(43, QtGui.QApplication.translate("extgen", "Senegal", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(44, QtGui.QApplication.translate("extgen", "Somalia", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(45, QtGui.QApplication.translate("extgen", "Sao Tome & Principe", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(46, QtGui.QApplication.translate("extgen", "Swaziland", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(47, QtGui.QApplication.translate("extgen", "Chad", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(48, QtGui.QApplication.translate("extgen", "Togo", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(49, QtGui.QApplication.translate("extgen", "Tunisia", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(50, QtGui.QApplication.translate("extgen", "Tanzania", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(51, QtGui.QApplication.translate("extgen", "Uganda", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(52, QtGui.QApplication.translate("extgen", "Mayotte", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(53, QtGui.QApplication.translate("extgen", "South Africa", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(54, QtGui.QApplication.translate("extgen", "Zambia", None, QtGui.QApplication.UnicodeUTF8))
        self.country.setItemText(55, QtGui.QApplication.translate("extgen", "Zimbabwe", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("extgen", "<html><head/><body><p><span style=\" font-weight:600;\">Output Site Randomized Points</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolOut.setText(QtGui.QApplication.translate("extgen", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVector), QtGui.QApplication.translate("extgen", "Load extent from layer or convas", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("extgen", "<html><head/><body><p>Load extent from either layer extent or canvas extent and generate random points, by clicking on the buttons.</p><p><br/></p><p><br/></p><p>Please report any problems to:</p><p><a href=\"http://geoportal.worldagroforestry.org/redmine/projects/qgisldsf/issues\"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">http://geoportal.worldagroforestry.org/redmine/projects/qgisldsf/issues</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), QtGui.QApplication.translate("extgen", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("extgen", "Important Fields * (Must Be Field)", None, QtGui.QApplication.UnicodeUTF8))

