# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_pprandpoints.ui'
#
# Created: Mon Oct 29 16:13:26 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ppgen(object):
    def setupUi(self, ppgen):
        ppgen.setObjectName(_fromUtf8("ppgen"))
        ppgen.resize(453, 371)
        self.tabWidget = QtGui.QTabWidget(ppgen)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 431, 291))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabVector = QtGui.QWidget()
        self.tabVector.setObjectName(_fromUtf8("tabVector"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabVector)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 411, 110))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.inShape = QtGui.QComboBox(self.verticalLayoutWidget)
        self.inShape.setObjectName(_fromUtf8("inShape"))
        self.verticalLayout.addWidget(self.inShape)
        self.label_12 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tabVector)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 110, 411, 61))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.outShape = QtGui.QLineEdit(self.verticalLayoutWidget_2)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName(_fromUtf8("outShape"))
        self.horizontalLayout_2.addWidget(self.outShape)
        self.toolOut = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.toolOut.setObjectName(_fromUtf8("toolOut"))
        self.horizontalLayout_2.addWidget(self.toolOut)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tabVector)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 170, 411, 81))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_4.addWidget(self.label_4)
        self.progressBar = QtGui.QProgressBar(self.verticalLayoutWidget_3)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.verticalLayout_4.addWidget(self.progressBar)
        self.tabWidget.addTab(self.tabVector, _fromUtf8(""))
        self.tabAbout = QtGui.QWidget()
        self.tabAbout.setObjectName(_fromUtf8("tabAbout"))
        self.label_7 = QtGui.QLabel(self.tabAbout)
        self.label_7.setGeometry(QtCore.QRect(10, 0, 411, 251))
        self.label_7.setScaledContents(False)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.tabWidget.addTab(self.tabAbout, _fromUtf8(""))
        self.label_5 = QtGui.QLabel(ppgen)
        self.label_5.setGeometry(QtCore.QRect(10, 350, 347, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.buttonBox_2 = QtGui.QDialogButtonBox(ppgen)
        self.buttonBox_2.setGeometry(QtCore.QRect(90, 310, 349, 27))
        self.buttonBox_2.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_2.setObjectName(_fromUtf8("buttonBox_2"))

        self.retranslateUi(ppgen)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("accepted()")), ppgen.accept)
        QtCore.QObject.connect(self.buttonBox_2, QtCore.SIGNAL(_fromUtf8("rejected()")), ppgen.reject)
        QtCore.QMetaObject.connectSlotsByName(ppgen)

    def retranslateUi(self, ppgen):
        ppgen.setWindowTitle(QtGui.QApplication.translate("ppgen", "Load Point or Polygon Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ppgen", "<html><head/><body><p><span style=\" font-weight:600;\">Input Polygon or Point Layer</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ppgen", "<html><head/><body><p><span style=\" font-weight:600;\">Enter name of site and select country</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ppgen", "Site Name*  [To be enabled in version 0.5]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ppgen", "<html><head/><body><p><span style=\" font-weight:600;\">Output Site Randomized Points</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolOut.setText(QtGui.QApplication.translate("ppgen", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ppgen", "<html><head/><body><p><span style=\" font-weight:600;\">Progress Bar</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVector), QtGui.QApplication.translate("ppgen", "Load Point or Polygon Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ppgen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Point and polygon Shapefile Uploader</span></p><p>This functionality of the plugin is to be used to load both point and polygon shapefiles, it is advisable to load a point shapefile with atleast one column with the name \'site\' so that the site name is associted with the cluster points</p><p><br/></p><p>Please report any problems to:</p><p><a href=\"http://geoportal.worldagroforestry.org/redmine/projects/qgisldsf/issues\"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">http://geoportal.worldagroforestry.org/redmine/projects/qgisldsf/issues</span></a></p><p><br/></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), QtGui.QApplication.translate("ppgen", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ppgen", "Important Fields * (Must Be Field)", None, QtGui.QApplication.UnicodeUTF8))

