# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_txtrandpoints.ui'
#
# Created: Mon Oct 29 16:15:04 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_txtgen(object):
    def setupUi(self, txtgen):
        txtgen.setObjectName(_fromUtf8("txtgen"))
        txtgen.resize(449, 455)
        self.tabWidget = QtGui.QTabWidget(txtgen)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 431, 371))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabVector = QtGui.QWidget()
        self.tabVector.setObjectName(_fromUtf8("tabVector"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabVector)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 411, 301))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.txtCsvPath = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.txtCsvPath.setReadOnly(True)
        self.txtCsvPath.setObjectName(_fromUtf8("txtCsvPath"))
        self.horizontalLayout_2.addWidget(self.txtCsvPath)
        self.btnSelectCsv = QtGui.QPushButton(self.verticalLayoutWidget)
        self.btnSelectCsv.setObjectName(_fromUtf8("btnSelectCsv"))
        self.horizontalLayout_2.addWidget(self.btnSelectCsv)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.shapeidcol = QtGui.QComboBox(self.verticalLayoutWidget)
        self.shapeidcol.setObjectName(_fromUtf8("shapeidcol"))
        self.horizontalLayout_3.addWidget(self.shapeidcol)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.longcol = QtGui.QComboBox(self.verticalLayoutWidget)
        self.longcol.setObjectName(_fromUtf8("longcol"))
        self.horizontalLayout_5.addWidget(self.longcol)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_6.addWidget(self.label_8)
        self.latcol = QtGui.QComboBox(self.verticalLayoutWidget)
        self.latcol.setObjectName(_fromUtf8("latcol"))
        self.horizontalLayout_6.addWidget(self.latcol)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.site = QtGui.QComboBox(self.verticalLayoutWidget)
        self.site.setObjectName(_fromUtf8("site"))
        self.horizontalLayout_7.addWidget(self.site)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self._2 = QtGui.QHBoxLayout()
        self._2.setObjectName(_fromUtf8("_2"))
        self.outShape = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.outShape.setReadOnly(True)
        self.outShape.setObjectName(_fromUtf8("outShape"))
        self._2.addWidget(self.outShape)
        self.toolOut = QtGui.QToolButton(self.verticalLayoutWidget)
        self.toolOut.setObjectName(_fromUtf8("toolOut"))
        self._2.addWidget(self.toolOut)
        self.verticalLayout.addLayout(self._2)
        self.tabWidget.addTab(self.tabVector, _fromUtf8(""))
        self.tabAbout = QtGui.QWidget()
        self.tabAbout.setObjectName(_fromUtf8("tabAbout"))
        self.label_10 = QtGui.QLabel(self.tabAbout)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 401, 331))
        self.label_10.setScaledContents(False)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(True)
        self.label_10.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tabAbout, _fromUtf8(""))
        self.label_9 = QtGui.QLabel(txtgen)
        self.label_9.setGeometry(QtCore.QRect(10, 430, 347, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.buttonBox = QtGui.QDialogButtonBox(txtgen)
        self.buttonBox.setGeometry(QtCore.QRect(30, 390, 409, 27))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))

        self.retranslateUi(txtgen)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), txtgen.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), txtgen.reject)
        QtCore.QMetaObject.connectSlotsByName(txtgen)

    def retranslateUi(self, txtgen):
        txtgen.setWindowTitle(QtGui.QApplication.translate("txtgen", "Load a CSV with points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("txtgen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Load CSV with (ID,Lon, Lat,Site,...) columns</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("txtgen", "Input CSV file:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSelectCsv.setText(QtGui.QApplication.translate("txtgen", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("txtgen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Select CSV Columns</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("txtgen", "Feature ID Column* :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("txtgen", "Longitude (X) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("txtgen", "Latitude (Y) :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("txtgen", "Site Column* :", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("txtgen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Output Shapefile</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.toolOut.setText(QtGui.QApplication.translate("txtgen", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabVector), QtGui.QApplication.translate("txtgen", "Load CSV File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("txtgen", "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Load point from a CSV file</span></p><p>It is advisable that the CSV loaded to the plugin, should be of the following format or has the columns in the following order and naming header.</p><p><span style=\" color:#ff0000;\">ID, X, Y, site</span></p><p><span style=\" font-weight:600;\">Where:</span></p><p align=\"center\">ID - site unique id</p><p align=\"center\">X - Longitude</p><p align=\"center\">Y - Latitude</p><p align=\"center\">Site - Name of the site</p><p>Please report any problems to:</p><p><a href=\"http://geoportal.worldagroforestry.org/redmine/projects/qgisldsf/issues\"><span style=\" font-size:9pt; text-decoration: underline; color:#0000ff;\">http://geoportal.worldagroforestry.org/redmine/projects/qgisldsf/issues</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), QtGui.QApplication.translate("txtgen", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("txtgen", "Important Fields * (Must Be Field)", None, QtGui.QApplication.UnicodeUTF8))

